version: 2

models:
  # Dim Customer
  - name: dim_customer
    description: "Customer dimension table"
    # required to enforce primary key constraints
    config:
      contract: {enforced: true}
    columns:
      - name: CustomerID
        description: "The primary key for the dim_customer table"
        data_type: int
        data_tests:
          - unique
          - not_null
        constraints:
          - type: not_null
          - type: primary_key
      - name: AddressLine1
        description: "Customer address line 1"
        data_type: string
      - name: AddressLine2
        description: "Customer address line 2"
        data_type: string
      - name: City
        description: "City"
        data_type: string
      - name: CompanyName
        description: "Company name"
        data_type: string
      - name: EmailAddress
        description: "Email address"
        data_type: string
      - name: FirstName
        description: "First name"
        data_type: string
      - name: LastName
        description: "Last name"
        data_type: string
      - name: MiddleName
        description: "Middle name"
        data_type: string
      - name: ModifiedDate
        description: "Last modified timestamp"
        data_type: timestamp
      - name: NameStyle
        description: "Name style (boolean)"
        data_type: boolean
      - name: Phone
        description: "Phone number"
        data_type: string
      - name: PostalCode
        description: "Postal code"
        data_type: string
      - name: SalesPerson
        description: "Salesperson name"
        data_type: string
      - name: StateProvince
        description: "State or province"
        data_type: string
      - name: Suffix
        description: "Name suffix"
        data_type: string
      - name: Title
        description: "Title"
        data_type: string


  # Dim Product
  - name: dim_product
    description: "Product dimension table"
    # required to enforce primary key constraints
    config:
      contract: {enforced: true}
    columns:
      - name: ProductID
        description: "The primary key for the dim_product table"
        data_type: int
        data_tests:
          - unique
          - not_null
        constraints:
          - type: not_null
          - type: primary_key
      - name: Color
        data_type: string
      - name: ListPrice
        data_type: decimal
      - name: ModifiedDate
        data_type: timestamp
      - name: ProductCategoryName
        data_type: string
      - name: ProductDescription
        data_type: string
      - name: ProductModelName
        data_type: string
      - name: ProductName
        data_type: string
      - name: Size
        data_type: string

  # Fact Sales
  - name: fact_sales
    description: "Sales fact table"
    # required to enforce primary key constraints
    config:
      contract: {enforced: true}
    columns:
      - name: SalesOrderID
        description: "The primary key for the fact_sales table"
        data_type: int
        data_tests:
          - unique
          - not_null
        constraints:
          - type: not_null
          - type: primary_key
      - name: ProductID
        description: "The foreign key to the dim_product table"
        data_type: int
        constraints:
          - type: foreign_key
            to: ref('dim_product')
            to_columns: [ProductID]
      - name: CustomerID
        description: "The foreign key to the dim_customer table"
        data_type: int
        constraints:
          - type: foreign_key
            to: ref('dim_customer')
            to_columns: [CustomerID]
      - name: BillToAddressID
        data_type: int
      - name: Comment
        data_type: string
      - name: ModifiedDate
        data_type: timestamp
      - name: OrderQty
        data_type: smallint
      - name: PurchaseOrderNumber
        data_type: string
      - name: SalesOrderNumber
        data_type: string
      - name: ShipMethod
        data_type: string
      - name: ShipToAddressID
        data_type: int
      - name: SubTotal
        data_type: decimal
      - name: TaxAmt
        data_type: decimal
      - name: TotalDue
        data_type: decimal
      - name: UnitPrice
        data_type: decimal
      - name: UnitPriceDiscount
        data_type: decimal