version: 2

models:
  # Dim Customer
  - name: dim_customer
    description: "Customer dimension table"
    columns:
      - name: CustomerID
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  # Dim Product
  - name: dim_product
    description: "Product dimension table"
    columns:
      - name: ProductID
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
          
  # Fact Sales
  - name: dim_sales
    description: "Sales fact table"
    columns:
      - name: SalesOrderID
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null